name: Cache Rancher VEX report

on:
  schedule:
    # Avoid the busiest top-of-hour period.
    - cron: '35 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cache-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Download VEX report metadata
        shell: bash
        run: |
          set -euo pipefail

          curl \
            --fail \
            --retry 3 \
            --retry-all-errors \
            --output "$GITHUB_WORKSPACE/.rancher.openvex.json.meta" \
            https://raw.githubusercontent.com/rancher/vexhub/refs/heads/main/reports/rancher.openvex.json

      - name: Check VEX cache
        id: vex-cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ runner.temp }}/rancher.openvex.json
          # This is a hash-of-a-hash, as the metadata file itself holds the SHA256.
          key: rancher-vex-v1-${{ hashFiles('.rancher.openvex.json.meta') }}
          lookup-only: true

      - name: Download Rancher VEX report
        if: steps.vex-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -euo pipefail

          curl \
            --fail \
            --location \
            --retry 3 \
            --retry-all-errors \
            --output "$RUNNER_TEMP/rancher.openvex.json" \
            https://github.com/rancher/vexhub/raw/refs/heads/main/reports/rancher.openvex.json

          jq --exit-status \
            'has("@context") and (.statements | type == "array")' \
            "$RUNNER_TEMP/rancher.openvex.json" \
            > /dev/null

      - name: Save VEX cache
        if: steps.vex-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ runner.temp }}/rancher.openvex.json
          key: rancher-vex-v1-${{ hashFiles('.rancher.openvex.json.meta') }}